baseURL = "/"

languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "WWU Cybersecurity Club"
    subtitle = "The homepage of the Western Washington University Cybersecurity Club"
    keywords = "wwu, western, university, cybersecurity, security, infosec, compsci"
    copyright = "Copyright 2021 WWU Cybersecurity Club"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "WWU Cybersecurity Club"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "resources"
	    name = "Resources"
	    url = "/resources"
	  [[languages.en.menu.main]]
	    identifier = "calendar"
	    name = "Calendar"
	    url = "/calendar"
